Algoritmo "exercicio12"
Var
  x1,y1,x2,y2,d:real
Inicio
           escreval("Insira o valor de x1 ")
      leia(x1)
           escreval("Insira o valor de y1")
      leia(y1)
           escreval("Insira o valor de x2")
      leia(x2)
              escreval("Insira valore y2")
      leia(y2)
      
      d<-raizQ((x2-x1)^2+(y2-y1)^2)
      escreval("A distancia entre os dois pontos é : ",d)
      

Fimalgoritmo